language: erlang

otp_release:
  - 17.0

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install curl jq screen
  - sudo chmod -R 0775 /var/run/screen
  - mkdir .gossiperl-daemon
  - cd .gossiperl-daemon
  - git clone https://github.com/gossiperl/gossiperl.git .
  - cd ..
  - chmod +x .gossiperl-daemon/test/run-for-unit-tests.sh
  - ./.gossiperl-daemon/test/run-for-unit-tests.sh

sudo: false

script: "rebar compile eunit"

notifications:
  email: false