language: erlang

otp_release:
  - 17.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install wget curl jq
  - "wget https://github.com/gossiperl/gossiperl/releases/download/${GOSSIPERL_V}/gossiperl-${GOSSIPERL_V}_all.deb"
  - "sudo dpkg -i gossiperl-{GOSSIPERL_V}_all.deb"
  - sudo /etc/gossiperl/start-and-wait.sh
  - sudo /etc/gossiperl/test-overlay.sh

sudo: true

script: "rebar compile eunit"

notifications:
  email: false